import { UserProfile, Gig, RewardItem, CreditTransaction, Conversation, Message, SafetyReport } from '../../shared/types/domain';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user_shalok',
    name: 'Shalok Dadhwal',
    email: 'shalok@neighborhoodhero.app',
    phone: '+91 98765 43210',
    profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    bio: 'CU Student & avid tech builder. Always happy to lend a helping hand in Sunny Enclave & Sector 125!',
    rating: 4.9,
    ratingCount: 18,
    totalCredits: 720,
    lifetimeCredits: 720,
    level: 4,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-08-01T10:00:00Z' },
      { badgeId: 'badge_helping_hand', unlockedAt: '2026-08-05T14:30:00Z' },
      { badgeId: 'badge_errand_runner', unlockedAt: '2026-08-10T12:00:00Z' },
      { badgeId: 'badge_tech_fixer', unlockedAt: '2026-08-15T18:00:00Z' }
    ],
    interests: ['Tech Help', 'Errands', 'Student Help', 'Groceries'],
    role: 'USER',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-07-15T08:00:00Z',
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'user_simran',
    name: 'Simran Kaur',
    email: 'simran.k@gmail.com',
    phone: '+91 98123 45678',
    profileImageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    bio: 'Designer based in Mohali Phase 3B2. Dog lover & occasional tutor.',
    rating: 5.0,
    ratingCount: 32,
    totalCredits: 1450,
    lifetimeCredits: 1450,
    level: 5,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-06-01T09:00:00Z' },
      { badgeId: 'badge_helping_hand', unlockedAt: '2026-06-10T11:00:00Z' },
      { badgeId: 'badge_super_helper', unlockedAt: '2026-07-20T16:00:00Z' },
      { badgeId: 'badge_pet_hero', unlockedAt: '2026-08-02T19:00:00Z' }
    ],
    interests: ['Pets', 'Tutoring', 'Household', 'Events'],
    role: 'USER',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-05-10T10:00:00Z',
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'user_arjun',
    name: 'Arjun Mehta',
    email: 'arjun.m@tricitygigs.in',
    phone: '+91 97788 99000',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec17',
    localityName: 'Sector 17',
    bio: 'Small business owner in Sector 17 & 34. Always looking for smart energetic helpers!',
    rating: 4.8,
    ratingCount: 45,
    totalCredits: 2800,
    lifetimeCredits: 2800,
    level: 6,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-04-01T10:00:00Z' },
      { badgeId: 'badge_10_gigs', unlockedAt: '2026-05-15T12:00:00Z' },
      { badgeId: 'badge_5_star', unlockedAt: '2026-07-01T15:00:00Z' }
    ],
    interests: ['Local Business', 'Delivery/Pickup', 'Events', 'Moving/Carrying'],
    role: 'ADMIN',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-03-01T12:00:00Z',
    lastActiveAt: new Date().toISOString()
  }
];

export const INITIAL_GIGS_SEED: Gig[] = [
  // --- KHARAR (10 Gigs) ---
  {
    id: 'gig_kh_1',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Need help carrying heavy grocery bags upstairs',
    description: 'Bought weekly groceries from Reliance Smart near Sector 125. Need someone to help carry 4 bags to the 3rd floor (no lift). Should take under 15 minutes!',
    category: 'Groceries',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    approxAddress: 'Near Sector 125 Market, Kharar',
    exactAddress: 'Flat 304, Block B, Sunny Heights, Sector 125, Kharar',
    latitude: 30.7432,
    longitude: 76.6621,
    budget: 150,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    distanceKm: 0.7
  },
  {
    id: 'gig_kh_2',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Python / Data Structures tutoring session (1 hr)',
    description: 'Looking for a computer science student in Kharar/Landran to review linked lists & basic binary search trees with my nephew before his college exam tomorrow.',
    category: 'Tutoring',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_landran',
    localityName: 'Landran Road',
    approxAddress: 'Near CGC Landran Gate 2, Kharar',
    exactAddress: 'House 88, Green Avenue, Landran Road, Kharar',
    latitude: 30.7340,
    longitude: 76.6690,
    budget: 400,
    creditReward: 50,
    urgency: 'SOON',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    distanceKm: 1.4
  },
  {
    id: 'gig_kh_3',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Pick up medical reports from Sunny Enclave Lab',
    description: 'Need someone passing by Sunny Enclave main road to pick up printed blood report copies from Lal PathLabs and drop them off near Sector 125.',
    category: 'Delivery/Pickup',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sunny',
    localityName: 'Sunny Enclave',
    approxAddress: 'Near Sunny Enclave Shopping Arcade',
    latitude: 30.7485,
    longitude: 76.6578,
    budget: 100,
    creditReward: 20,
    urgency: 'URGENT',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    distanceKm: 0.9
  },
  {
    id: 'gig_kh_4',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Evening Dog Walking in Sector 115',
    description: 'Golden Retriever named Bruno needs a 30-minute energetic walk around Sector 115 park in the evening. Friendly dog, leash provided!',
    category: 'Pets',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec115',
    localityName: 'Sector 115',
    approxAddress: 'Near Central Park, Sector 115',
    latitude: 30.7391,
    longitude: 76.6510,
    budget: 200,
    creditReward: 30,
    urgency: 'TODAY',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    distanceKm: 1.8
  },
  {
    id: 'gig_kh_5',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Assemble IKEA Study Desk',
    description: 'Unboxed a flat-pack study table. Looking for someone handy with a screwdriver/Allen key to assemble it.',
    category: 'Repairs',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    approxAddress: 'Sector 125, Kharar',
    latitude: 30.7440,
    longitude: 76.6630,
    budget: 350,
    creditReward: 40,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 200 * 60000).toISOString(),
    distanceKm: 0.8
  },
  {
    id: 'gig_kh_6',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Wi-Fi Router & Printer Setup Assistance',
    description: 'Need help connecting a new Airtel Fiber router to my HP Wireless printer and configuring laptop print drivers.',
    category: 'Tech Help',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_khanpur',
    localityName: 'Khanpur',
    approxAddress: 'Near Khanpur Chowk, Kharar',
    latitude: 30.7510,
    longitude: 76.6450,
    budget: 250,
    creditReward: 35,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 300 * 60000).toISOString(),
    distanceKm: 2.1
  },
  {
    id: 'gig_kh_7',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Help moving 5 boxes of engineering books',
    description: 'Relocating room near Kharar Bus Stand. Need an extra pair of hands to load 5 heavy boxes into a taxi.',
    category: 'Moving/Carrying',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_busstand',
    localityName: 'Kharar Bus Stand Area',
    approxAddress: 'Near Kharar Flyover Bus Stop',
    latitude: 30.7455,
    longitude: 76.6420,
    budget: 200,
    creditReward: 30,
    urgency: 'URGENT',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    distanceKm: 2.5
  },
  {
    id: 'gig_kh_8',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Flyer distribution for local café opening',
    description: 'Pass out 100 promotional opening discount flyers to students near Landran college campus gate.',
    category: 'Local Business',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_landran',
    localityName: 'Landran Road',
    approxAddress: 'Landran Campus Gate',
    latitude: 30.7350,
    longitude: 76.6680,
    budget: 300,
    creditReward: 35,
    urgency: 'SOON',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 400 * 60000).toISOString(),
    distanceKm: 1.5
  },
  {
    id: 'gig_kh_9',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Water houseplants while away for weekend',
    description: 'Going out of town for 2 days. Need a trustworthy neighbor in Sunny Enclave to drop by once and water balcony plants.',
    category: 'Household',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sunny',
    localityName: 'Sunny Enclave',
    approxAddress: 'Sunny Enclave Sector 4',
    latitude: 30.7490,
    longitude: 76.6585,
    budget: 150,
    creditReward: 20,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~15 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 500 * 60000).toISOString(),
    distanceKm: 1.0
  },
  {
    id: 'gig_kh_10',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Lab Notebook Formatting in MS Word',
    description: 'Need a student familiar with Word table of contents & page layout to format 30 pages of typed notes cleanly.',
    category: 'Student Help',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    approxAddress: 'Sector 125, Kharar',
    latitude: 30.7425,
    longitude: 76.6615,
    budget: 250,
    creditReward: 30,
    urgency: 'TODAY',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 600 * 60000).toISOString(),
    distanceKm: 0.6
  },

  // --- MOHALI (15 Gigs) ---
  {
    id: 'gig_mo_1',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Pick up dry cleaning from Phase 3B2 Market',
    description: 'Need 3 suits picked up from White Tiger Cleaners in Phase 3B2 market and delivered to Phase 7.',
    category: 'Errands',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    approxAddress: 'Phase 3B2 Market, Mohali',
    latitude: 30.7105,
    longitude: 76.7170,
    budget: 150,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    distanceKm: 2.2
  },
  {
    id: 'gig_mo_2',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Product Photography for Artisanal Candles',
    description: 'Local Instagram candle brand in Sector 70 needs someone with a good phone camera / DSLR to take 10 crisp product photos on a white backdrop.',
    category: 'Local Business',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec70',
    localityName: 'Sector 70',
    approxAddress: 'Sector 70 Market, Mohali',
    latitude: 30.7020,
    longitude: 76.7010,
    budget: 500,
    creditReward: 50,
    urgency: 'SOON',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
    distanceKm: 3.1
  },
  {
    id: 'gig_mo_3',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Dog Sitter for 2 hours in Phase 7',
    description: 'Looking for a gentle dog lover to stay with my beagle while I attend a 2-hour online exam. He loves playing fetch!',
    category: 'Pets',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p7',
    localityName: 'Phase 7',
    approxAddress: 'Near Phase 7 Park, Mohali',
    latitude: 30.7040,
    longitude: 76.7120,
    budget: 300,
    creditReward: 35,
    urgency: 'TODAY',
    estimatedDuration: '~2 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 75 * 60000).toISOString(),
    distanceKm: 2.8
  },
  {
    id: 'gig_mo_4',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Elderly assistance: Buying fresh vegetables',
    description: 'My grandmother needs someone to accompany her or buy fresh veggies from Sector 68 Apni Mandi.',
    category: 'Groceries',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec68',
    localityName: 'Sector 68',
    approxAddress: 'Sector 68 Apni Mandi Ground',
    latitude: 30.6910,
    longitude: 76.7250,
    budget: 200,
    creditReward: 30,
    urgency: 'TODAY',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 150 * 60000).toISOString(),
    distanceKm: 3.5
  },
  {
    id: 'gig_mo_5',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Class 10 CBSE Math Trigonometry Practice',
    description: 'Looking for a engineering student to solve 10 previous year trigonometry questions with a Class 10 student in Sector 71.',
    category: 'Tutoring',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec71',
    localityName: 'Sector 71',
    approxAddress: 'Sector 71, Mohali',
    latitude: 30.7090,
    longitude: 76.6960,
    budget: 350,
    creditReward: 40,
    urgency: 'SOON',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    distanceKm: 2.6
  },
  {
    id: 'gig_mo_6',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Fix Squeaky Door Hinge & Hang Wall Mirror',
    description: 'Need basic handyman tools (drill/screws) to hang a 3x2 ft wall mirror securely in Phase 5.',
    category: 'Repairs',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p5',
    localityName: 'Phase 5',
    approxAddress: 'Phase 5 Market area',
    latitude: 30.7180,
    longitude: 76.7210,
    budget: 250,
    creditReward: 30,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 240 * 60000).toISOString(),
    distanceKm: 2.0
  },
  {
    id: 'gig_mo_7',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Help organize IT Park office inventory',
    description: 'Startup in Sector 66 needs help counting & cataloging 40 laptop accessories and cables into an Excel sheet.',
    category: 'Local Business',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec66',
    localityName: 'Sector 66',
    approxAddress: 'JLPL Industrial Area, Sector 66',
    latitude: 30.6780,
    longitude: 76.7320,
    budget: 450,
    creditReward: 45,
    urgency: 'SOON',
    estimatedDuration: '~1.5 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 320 * 60000).toISOString(),
    distanceKm: 4.2
  },
  {
    id: 'gig_mo_8',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Deliver document package to Sector 79',
    description: 'Sealed agreement documents need urgent bike delivery from Phase 1 to Sector 79 before 5 PM.',
    category: 'Delivery/Pickup',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec79',
    localityName: 'Sector 79',
    approxAddress: 'Sector 79 Commercial Complex',
    latitude: 30.6890,
    longitude: 76.7120,
    budget: 180,
    creditReward: 25,
    urgency: 'URGENT',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    distanceKm: 3.0
  },
  {
    id: 'gig_mo_9',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'MacBook M2 Software & Xcode Setup',
    description: 'Need help installing Homebrew, Flutter SDK, Node.js and Cocoapods on a fresh MacBook Air in Sector 67.',
    category: 'Tech Help',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec67',
    localityName: 'Sector 67',
    approxAddress: 'Sector 67 Residential Area',
    latitude: 30.6840,
    longitude: 76.7280,
    budget: 400,
    creditReward: 40,
    urgency: 'TODAY',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 140 * 60000).toISOString(),
    distanceKm: 3.8
  },
  {
    id: 'gig_mo_10',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Event registration desk helper for 2 hours',
    description: 'Community tech meetup in Phase 8 needs a friendly helper to check in guests using a QR scanner tablet app.',
    category: 'Events',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p8',
    localityName: 'Phase 8',
    approxAddress: 'CP67 Mall Convention Hall',
    latitude: 30.6970,
    longitude: 76.7080,
    budget: 500,
    creditReward: 50,
    urgency: 'SOON',
    estimatedDuration: '~2 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 410 * 60000).toISOString(),
    distanceKm: 2.7
  },
  {
    id: 'gig_mo_11',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Unpack 6 boxes of clothes after shifting',
    description: 'Recently moved to Phase 1. Need assistance folding clothes and putting hangers in closets.',
    category: 'Household',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p1',
    localityName: 'Phase 1',
    approxAddress: 'Phase 1, Mohali',
    latitude: 30.7290,
    longitude: 76.7150,
    budget: 250,
    creditReward: 30,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 520 * 60000).toISOString(),
    distanceKm: 2.0
  },
  {
    id: 'gig_mo_12',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Help move sofa from living room to balcony',
    description: 'Requires two people to carry a 3-seater sofa out to the terrace in Sector 80.',
    category: 'Moving/Carrying',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec80',
    localityName: 'Sector 80',
    approxAddress: 'Sector 80, Mohali',
    latitude: 30.6830,
    longitude: 76.7180,
    budget: 200,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 130 * 60000).toISOString(),
    distanceKm: 3.4
  },
  {
    id: 'gig_mo_13',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Spoken English practice partner (1 hr)',
    description: 'Looking for a fluent English speaker for conversational practice over coffee at Phase 3B2 market.',
    category: 'Student Help',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    approxAddress: 'Phase 3B2 Cafe Area',
    latitude: 30.7100,
    longitude: 76.7175,
    budget: 250,
    creditReward: 30,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 610 * 60000).toISOString(),
    distanceKm: 2.1
  },
  {
    id: 'gig_mo_14',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Pick up birthday cake from Nik Bakers Phase 3B2',
    description: 'Pre-ordered custom cake needs careful car or smooth scooter transport to Sector 70 house.',
    category: 'Delivery/Pickup',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    approxAddress: 'Nik Bakers Phase 3B2',
    latitude: 30.7110,
    longitude: 76.7165,
    budget: 150,
    creditReward: 20,
    urgency: 'URGENT',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    distanceKm: 2.2
  },
  {
    id: 'gig_mo_15',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Cat feeding & litter box check in Sector 68',
    description: 'Persian cat needs fresh food bowl and water refill once today in Sector 68 house.',
    category: 'Pets',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec68',
    localityName: 'Sector 68',
    approxAddress: 'Sector 68, Mohali',
    latitude: 30.6915,
    longitude: 76.7255,
    budget: 150,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 170 * 60000).toISOString(),
    distanceKm: 3.5
  },

  // --- CHANDIGARH (15 Gigs) ---
  {
    id: 'gig_ch_1',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Need Panjab University library books returned',
    description: 'Have 3 library books to return to AC Joshi Library inside PU Sector 14 campus. Books are ready at Sector 15 hostel.',
    category: 'Student Help',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec15',
    localityName: 'Sector 15',
    approxAddress: 'Near Sector 15 Market, Chandigarh',
    latitude: 30.7580,
    longitude: 76.7720,
    budget: 150,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 50 * 60000).toISOString(),
    distanceKm: 4.8
  },
  {
    id: 'gig_ch_2',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Help standing in queue at Sector 17 Passport Seva Kendra',
    description: 'Need someone to hold a spot in the early morning document verification line for 30 minutes in Sector 17.',
    category: 'Errands',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec17',
    localityName: 'Sector 17 (City Center)',
    approxAddress: 'Passport Office, Sector 17, Chandigarh',
    latitude: 30.7410,
    longitude: 76.7850,
    budget: 200,
    creditReward: 30,
    urgency: 'URGENT',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    distanceKm: 5.2
  },
  {
    id: 'gig_ch_3',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Pick up medical prescription from Sector 22 Chemist',
    description: 'Senior citizen needs specific diabetes medication picked up from Sector 22 chemist shop and delivered to Sector 35.',
    category: 'Groceries',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec22',
    localityName: 'Sector 22',
    approxAddress: 'Sector 22 Market, Chandigarh',
    latitude: 30.7340,
    longitude: 76.7770,
    budget: 150,
    creditReward: 20,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 85 * 60000).toISOString(),
    distanceKm: 4.9
  },
  {
    id: 'gig_ch_4',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Figma UI/UX Feedback & Review Session',
    description: 'Design startup in Sector 34 needs a student/user to test a new mobile wireframe and provide 30 mins of candid feedback.',
    category: 'Tech Help',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec34',
    localityName: 'Sector 34',
    approxAddress: 'Sector 34 Coaching Hub',
    latitude: 30.7220,
    longitude: 76.7680,
    budget: 350,
    creditReward: 40,
    urgency: 'SOON',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 160 * 60000).toISOString(),
    distanceKm: 4.5
  },
  {
    id: 'gig_ch_5',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Guitar Chords Basics Lesson for Beginner',
    description: 'Looking for a music student in Sector 35 to teach basic acoustic guitar chords (G, C, D, Em) for 45 minutes.',
    category: 'Tutoring',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec35',
    localityName: 'Sector 35',
    approxAddress: 'Sector 35, Chandigarh',
    latitude: 30.7260,
    longitude: 76.7610,
    budget: 300,
    creditReward: 35,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 290 * 60000).toISOString(),
    distanceKm: 4.3
  },
  {
    id: 'gig_ch_6',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Help carry luggage from ISBT 43 Bus Stand',
    description: 'Arriving at ISBT Sector 43 with 2 heavy suitcases. Need a quick hand moving them from platform to auto stand.',
    category: 'Moving/Carrying',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec43',
    localityName: 'Sector 43',
    approxAddress: 'ISBT Sector 43 Main Exit',
    latitude: 30.7140,
    longitude: 76.7510,
    budget: 150,
    creditReward: 20,
    urgency: 'URGENT',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    distanceKm: 3.9
  },
  {
    id: 'gig_ch_7',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Bicycle chain tuning & brake adjustment',
    description: 'My gear bicycle chain keeps slipping in Sector 44. Looking for a local cyclist/repair enthusiast to tune derailleur screws.',
    category: 'Repairs',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec44',
    localityName: 'Sector 44',
    approxAddress: 'Sector 44 Park',
    latitude: 30.7110,
    longitude: 76.7590,
    budget: 200,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 220 * 60000).toISOString(),
    distanceKm: 4.1
  },
  {
    id: 'gig_ch_8',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Pug Dog Walk in Sector 49 Society',
    description: 'Gentle 20-minute evening walk inside society premises in Sector 49 for a friendly 3-year-old Pug.',
    category: 'Pets',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec49',
    localityName: 'Sector 49',
    approxAddress: 'Sector 49 Housing Society',
    latitude: 30.6970,
    longitude: 76.7450,
    budget: 150,
    creditReward: 20,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 340 * 60000).toISOString(),
    distanceKm: 3.6
  },
  {
    id: 'gig_ch_9',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Packaging & Labeling 20 Boutique Orders',
    description: 'Local clothing boutique in Sector 50 needs assistance wrapping items in tissue paper and pasting courier labels.',
    category: 'Local Business',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec50',
    localityName: 'Sector 50',
    approxAddress: 'Sector 50 Shopping Complex',
    latitude: 30.6920,
    longitude: 76.7520,
    budget: 300,
    creditReward: 35,
    urgency: 'SOON',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 430 * 60000).toISOString(),
    distanceKm: 3.8
  },
  {
    id: 'gig_ch_10',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Deliver hard disk to IT park employee',
    description: 'External backup hard drive needs secure transport from Sector 15 to IT Park Phase 1.',
    category: 'Delivery/Pickup',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec15',
    localityName: 'Sector 15',
    approxAddress: 'Sector 15, Chandigarh',
    latitude: 30.7570,
    longitude: 76.7730,
    budget: 200,
    creditReward: 30,
    urgency: 'TODAY',
    estimatedDuration: '~35 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 95 * 60000).toISOString(),
    distanceKm: 4.7
  },
  {
    id: 'gig_ch_11',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'French A1 Conversation Practice',
    description: 'Looking for a student learning French to practice basic introduction vocabulary for 45 minutes.',
    category: 'Tutoring',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec17',
    localityName: 'Sector 17 (City Center)',
    approxAddress: 'Sector 17 Plaza Cafe',
    latitude: 30.7415,
    longitude: 76.7855,
    budget: 300,
    creditReward: 35,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 550 * 60000).toISOString(),
    distanceKm: 5.3
  },
  {
    id: 'gig_ch_12',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Help set up Smart TV & Amazon FireStick',
    description: 'Elderly couple in Sector 22 needs help logging into Prime Video, Hotstar & Wi-Fi on new Smart TV.',
    category: 'Tech Help',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec22',
    localityName: 'Sector 22',
    approxAddress: 'Sector 22-B, Chandigarh',
    latitude: 30.7345,
    longitude: 76.7775,
    budget: 250,
    creditReward: 30,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 210 * 60000).toISOString(),
    distanceKm: 4.9
  },
  {
    id: 'gig_ch_13',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Pick up Gopal Sweets Box from Sector 35',
    description: 'Need a boxed sweet gift collected from Sector 35 store and delivered to Sector 43 office.',
    category: 'Groceries',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec35',
    localityName: 'Sector 35',
    approxAddress: 'Gopal Sweets Sector 35',
    latitude: 30.7265,
    longitude: 76.7615,
    budget: 150,
    creditReward: 20,
    urgency: 'URGENT',
    estimatedDuration: '~25 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    distanceKm: 4.3
  },
  {
    id: 'gig_ch_14',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Poster design critique for college fest',
    description: 'Design student wanted to review a Photoshop flyer layout for 20 minutes online or in Sector 34.',
    category: 'Student Help',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec34',
    localityName: 'Sector 34',
    approxAddress: 'Sector 34 Library',
    latitude: 30.7225,
    longitude: 76.7685,
    budget: 200,
    creditReward: 25,
    urgency: 'SOON',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 310 * 60000).toISOString(),
    distanceKm: 4.5
  },
  {
    id: 'gig_ch_15',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Help water garden plants in Sector 44',
    description: 'Fenced lawn needs 20 minutes of hose watering during morning hours.',
    category: 'Household',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec44',
    localityName: 'Sector 44',
    approxAddress: 'Sector 44-D, Chandigarh',
    latitude: 30.7115,
    longitude: 76.7595,
    budget: 150,
    creditReward: 20,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 480 * 60000).toISOString(),
    distanceKm: 4.1
  },

  // --- PANCHKULA (10 Gigs) ---
  {
    id: 'gig_pa_1',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Dog Walking around Sector 8 Panchkula Park',
    description: 'Labrador retriever needs a 30-minute evening walk near Sector 8 market park. Very gentle & friendly!',
    category: 'Pets',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec8',
    localityName: 'Sector 8',
    approxAddress: 'Near Sector 8 Market, Panchkula',
    latitude: 30.6910,
    longitude: 76.8580,
    budget: 200,
    creditReward: 25,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    distanceKm: 9.5
  },
  {
    id: 'gig_pa_2',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Pick up bakery order from Sector 5 Panchkula',
    description: 'Need a boxed hamper collected from Sector 5 bakery and dropped off at Sector 11 home.',
    category: 'Delivery/Pickup',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec5',
    localityName: 'Sector 5',
    approxAddress: 'Sector 5 Commercial Belt',
    latitude: 30.6980,
    longitude: 76.8520,
    budget: 150,
    creditReward: 20,
    urgency: 'TODAY',
    estimatedDuration: '~25 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 115 * 60000).toISOString(),
    distanceKm: 9.1
  },
  {
    id: 'gig_pa_3',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Laptop RAM upgrade & SSD clone help',
    description: 'Looking for a tech student in Panchkula to help swap an 8GB RAM stick and clone C: drive to a new NVMe SSD.',
    category: 'Tech Help',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec9',
    localityName: 'Sector 9',
    approxAddress: 'Sector 9 Market, Panchkula',
    latitude: 30.6860,
    longitude: 76.8550,
    budget: 400,
    creditReward: 40,
    urgency: 'SOON',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 195 * 60000).toISOString(),
    distanceKm: 9.3
  },
  {
    id: 'gig_pa_4',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Class 8 Science Light & Shadow chapter tutoring',
    description: 'Need a tutor for 1 hour to explain ray diagrams & pinhole camera concepts to a student in Sector 10.',
    category: 'Tutoring',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec10',
    localityName: 'Sector 10',
    approxAddress: 'Sector 10, Panchkula',
    latitude: 30.6830,
    longitude: 76.8620,
    budget: 300,
    creditReward: 35,
    urgency: 'TODAY',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 280 * 60000).toISOString(),
    distanceKm: 9.8
  },
  {
    id: 'gig_pa_5',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Help carry 3 ceramic planters to garden terrace',
    description: 'Potted plants are delivered at main gate in Sector 11. Need help carrying them upstairs.',
    category: 'Moving/Carrying',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec11',
    localityName: 'Sector 11',
    approxAddress: 'Sector 11, Panchkula',
    latitude: 30.6890,
    longitude: 76.8680,
    budget: 200,
    creditReward: 25,
    urgency: 'URGENT',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    distanceKm: 10.2
  },
  {
    id: 'gig_pa_6',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Pick up Organic Honey jar from Sector 12',
    description: 'Pick up 1kg farm honey jar from Sector 12 and deliver near Sector 20 Panchkula.',
    category: 'Groceries',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec12',
    localityName: 'Sector 12',
    approxAddress: 'Sector 12 A, Panchkula',
    latitude: 30.6960,
    longitude: 76.8650,
    budget: 150,
    creditReward: 20,
    urgency: 'TODAY',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 145 * 60000).toISOString(),
    distanceKm: 10.0
  },
  {
    id: 'gig_pa_7',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Handyman to fix loose cabinet door handle',
    description: 'Kitchen wooden drawer handle screw is stripped in Sector 15. Requires handyman touch or wood filler.',
    category: 'Repairs',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec15',
    localityName: 'Sector 15',
    approxAddress: 'Sector 15, Panchkula',
    latitude: 30.6780,
    longitude: 76.8500,
    budget: 200,
    creditReward: 25,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~20 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 380 * 60000).toISOString(),
    distanceKm: 9.0
  },
  {
    id: 'gig_pa_8',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Storefront window banner hanging helper',
    description: 'Clothing store in Sector 20 needs help climbing a step ladder and fixing a 6x3 ft vinyl banner with cable ties.',
    category: 'Local Business',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec20',
    localityName: 'Sector 20',
    approxAddress: 'Sector 20 Market Complex',
    latitude: 30.6650,
    longitude: 76.8420,
    budget: 300,
    creditReward: 35,
    urgency: 'SOON',
    estimatedDuration: '~30 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 250 * 60000).toISOString(),
    distanceKm: 8.5
  },
  {
    id: 'gig_pa_9',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Pick up couriered parcel from Post Office',
    description: 'Registered parcel waiting at Sector 8 Head Post Office needs collection with authorization letter.',
    category: 'Errands',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec8',
    localityName: 'Sector 8',
    approxAddress: 'Sector 8 Head Post Office',
    latitude: 30.6915,
    longitude: 76.8585,
    budget: 180,
    creditReward: 25,
    urgency: 'TODAY',
    estimatedDuration: '~35 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
    distanceKm: 9.5
  },
  {
    id: 'gig_pa_10',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Canine Feeding & Water Bowl Refill',
    description: 'Friendly German Shepherd in Sector 5 needs afternoon dry food & water check.',
    category: 'Pets',
    cityId: 'city_panchkula',
    cityName: 'Panchkula',
    localityId: 'loc_pa_sec5',
    localityName: 'Sector 5',
    approxAddress: 'Sector 5, Panchkula',
    latitude: 30.6985,
    longitude: 76.8525,
    budget: 150,
    creditReward: 20,
    urgency: 'SOON',
    estimatedDuration: '~15 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 420 * 60000).toISOString(),
    distanceKm: 9.1
  }
];

export const INITIAL_REWARDS_SEED: RewardItem[] = [
  {
    id: 'reward_cafe_100',
    name: '₹100 Local Café Voucher',
    description: 'Redeemable for artisanal coffee, cold brew, or shakes at partner cafés across Kharar, Mohali & Chandigarh.',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=80',
    creditCost: 500,
    stock: 45,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Brew & Bean Co.',
    redemptionInstructions: 'Show the generated 8-digit voucher code to the cashier before placing your order.',
    isActive: true
  },
  {
    id: 'reward_hero_stickers',
    name: 'Neighborhood Hero Sticker Pack',
    description: 'High-quality waterproof vinyl stickers featuring original Neighborhood Hero emblems for laptops & helmets.',
    imageUrl: 'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=400&q=80',
    creditCost: 1000,
    stock: 20,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Collect from your nearest community hub or provide postal address upon redemption.',
    isActive: true
  },
  {
    id: 'reward_hero_tshirt',
    name: 'Branded Hero Tech T-Shirt',
    description: 'Breathable dry-fit black graphic t-shirt with electric cyan Hero insignia on chest.',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    creditCost: 1500,
    stock: 12,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Select your size (S, M, L, XL) and pick up at the weekly Tricity Hero meetup.',
    isActive: true
  },
  {
    id: 'reward_dining_500',
    name: '₹500 Tricity Restaurant Pass',
    description: 'Enjoy ₹500 discount on your bill at select top-rated dining spots in Sector 35 Chandigarh & Phase 3B2 Mohali.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    creditCost: 2000,
    stock: 8,
    cityIds: ['city_mohali', 'city_chandigarh'],
    partnerName: 'Tricity Gourmet Club',
    redemptionInstructions: 'Present digital coupon at billing. Valid on minimum bill of ₹800.',
    isActive: true
  },
  {
    id: 'reward_hero_jacket',
    name: 'Premium Hero Windbreaker Jacket',
    description: 'Exclusive waterproof urban reflector jacket awarded to high-tier community champions.',
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=400&q=80',
    creditCost: 5000,
    stock: 3,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Admin team will contact you directly for custom sizing and doorstep delivery.',
    isActive: true
  }
];

export const INITIAL_TRANSACTIONS_SEED: CreditTransaction[] = [
  {
    id: 'tx_init_1',
    userId: 'user_shalok',
    amount: 500,
    type: 'EARN',
    reason: 'Completed 15 neighborhood missions',
    createdAt: '2026-08-01T12:00:00Z'
  },
  {
    id: 'tx_init_2',
    userId: 'user_shalok',
    amount: 100,
    type: 'BONUS',
    reason: 'First Mission & 5-Star Streak Bonuses',
    createdAt: '2026-08-10T14:30:00Z'
  },
  {
    id: 'tx_init_3',
    userId: 'user_shalok',
    amount: 120,
    type: 'EARN',
    reason: 'Completed Python Tutoring & Grocery Tasks',
    createdAt: '2026-08-18T09:15:00Z'
  }
];
