import { UserProfile, Gig, RewardItem, CreditTransaction, Conversation, Message, SafetyReport } from '../../shared/types/domain';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user_shalok',
    name: 'Shalok Dadhwal',
    email: 'shalok@neighborhoodhero.app',
    phone: '+91 98765 43210',
    profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    bio: 'CU Student & avid tech builder. Always happy to lend a helping hand in Sunny Enclave & Sector 125!',
    rating: 4.9,
    ratingCount: 18,
    totalCredits: 720,
    lifetimeCredits: 720,
    level: 4,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-08-01T10:00:00Z' },
      { badgeId: 'badge_helping_hand', unlockedAt: '2026-08-05T14:30:00Z' },
      { badgeId: 'badge_errand_runner', unlockedAt: '2026-08-10T12:00:00Z' },
      { badgeId: 'badge_tech_fixer', unlockedAt: '2026-08-15T18:00:00Z' }
    ],
    interests: ['Tech Help', 'Errands', 'Student Help', 'Groceries'],
    role: 'USER',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-07-15T08:00:00Z',
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'user_simran',
    name: 'Simran Kaur',
    email: 'simran.k@gmail.com',
    phone: '+91 98123 45678',
    profileImageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    bio: 'Designer based in Mohali Phase 3B2. Dog lover & occasional tutor.',
    rating: 5.0,
    ratingCount: 32,
    totalCredits: 1450,
    lifetimeCredits: 1450,
    level: 5,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-06-01T09:00:00Z' },
      { badgeId: 'badge_helping_hand', unlockedAt: '2026-06-10T11:00:00Z' },
      { badgeId: 'badge_super_helper', unlockedAt: '2026-07-20T16:00:00Z' },
      { badgeId: 'badge_pet_hero', unlockedAt: '2026-08-02T19:00:00Z' }
    ],
    interests: ['Pets', 'Tutoring', 'Household', 'Events'],
    role: 'USER',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-05-10T10:00:00Z',
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'user_arjun',
    name: 'Arjun Mehta',
    email: 'arjun.m@tricitygigs.in',
    phone: '+91 97788 99000',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec17',
    localityName: 'Sector 17',
    bio: 'Small business owner in Sector 17 & 34. Always looking for smart energetic helpers!',
    rating: 4.8,
    ratingCount: 45,
    totalCredits: 2800,
    lifetimeCredits: 2800,
    level: 6,
    badges: [
      { badgeId: 'badge_first_gig', unlockedAt: '2026-04-01T10:00:00Z' },
      { badgeId: 'badge_10_gigs', unlockedAt: '2026-05-15T12:00:00Z' },
      { badgeId: 'badge_5_star', unlockedAt: '2026-07-01T15:00:00Z' }
    ],
    interests: ['Local Business', 'Delivery/Pickup', 'Events', 'Moving/Carrying'],
    role: 'ADMIN',
    isVerified: true,
    isBlocked: false,
    createdAt: '2026-03-01T12:00:00Z',
    lastActiveAt: new Date().toISOString()
  }
];

export const INITIAL_GIGS_SEED: Gig[] = [
  // --- KHARAR (Civic Drives & Emergency Assistance) ---
  {
    id: 'gig_kh_1',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Ajit Sarovar Lake Waterfront Plastic Cleanup Drive',
    description: 'Critical plastic garbage, bottles & floating waste spotted polluting the Ajit Sarovar waterfront. Organizing a Sunday Community Clean Drive ("Hustle Sunday") to clear 50kg+ waste with local heroes. Gloves & bags provided!',
    category: 'Civic Clean Drive 🧹',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    approxAddress: 'Ajit Sarovar Lakefront, Sector 125, Kharar',
    exactAddress: 'Ajit Sarovar Main Entrance Ghat, Kharar',
    latitude: 30.7485,
    longitude: 76.6578,
    budget: 0,
    creditReward: 350,
    urgency: 'URGENT',
    estimatedDuration: '~2 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    distanceKm: 0.7,
    isCommunityEvent: true,
    eventDate: 'SUNDAY • 8:00 AM',
    requiredVolunteers: 12,
    joinedVolunteersCount: 7
  },
  {
    id: 'gig_kh_2',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'URGENT: O+ Blood Donor Required - Civil Hospital Kharar',
    description: 'Emergency blood donation request for an accident victim undergoing surgery at Civil Hospital Kharar. Requires 2 units of O+ blood. Transport assistance & hospital coordination provided.',
    category: 'Medical Emergency 🩸',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_khanpur',
    localityName: 'Khanpur',
    approxAddress: 'Civil Hospital Blood Bank, Khanpur, Kharar',
    exactAddress: 'Emergency Ward, Civil Hospital Kharar',
    latitude: 30.7510,
    longitude: 76.6450,
    budget: 0,
    creditReward: 500,
    urgency: 'URGENT',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    distanceKm: 1.4
  },
  {
    id: 'gig_kh_3',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Clear Blocked Storm Drain (Prevent School Flooding)',
    description: 'Heavy monsoon rainfall clogged the storm water drain near Primary School Sector 125 with tree branches & mud debris. Need 4 community heroes to clear the channel before tomorrow morning classes.',
    category: 'Infrastructure Repair ⚡',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec125',
    localityName: 'Sector 125',
    approxAddress: 'Near Govt Primary School, Sector 125',
    latitude: 30.7432,
    longitude: 76.6621,
    budget: 0,
    creditReward: 300,
    urgency: 'TODAY',
    estimatedDuration: '~1.5 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    distanceKm: 0.9,
    isCommunityEvent: true,
    eventDate: 'TODAY • 4:30 PM',
    requiredVolunteers: 4,
    joinedVolunteersCount: 2
  },
  {
    id: 'gig_kh_4',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Dark Alleyway Safety Light Installation & Ward Report',
    description: '3 municipal streetlights are out along the Girls PG road in Sector 115 creating a major safety concern at night. Installing 2 temporary solar motion sensor lights & filing an official municipal complaint.',
    category: 'Public Safety 🛡️',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sec115',
    localityName: 'Sector 115',
    approxAddress: 'Near Central Park PG Lane, Sector 115',
    latitude: 30.7391,
    longitude: 76.6510,
    budget: 0,
    creditReward: 250,
    urgency: 'SOON',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    distanceKm: 1.8
  },
  {
    id: 'gig_kh_5',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'Injured Stray Dog Emergency Transport to SPCA Vet',
    description: 'Rescued an injured stray pup near Sunny Enclave. Need a compassionate hero with a car or pet carrier to safely transport the puppy to SPCA Animal Hospital in Sector 38.',
    category: 'Animal Rescue 🐾',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_sunny',
    localityName: 'Sunny Enclave',
    approxAddress: 'Sunny Enclave Market Sector 4',
    latitude: 30.7490,
    longitude: 76.6585,
    budget: 0,
    creditReward: 200,
    urgency: 'URGENT',
    estimatedDuration: '~45 min',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    distanceKm: 1.1
  },
  {
    id: 'gig_kh_6',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Surplus Bakery Food Drive for Local Night Shelter',
    description: 'A local Kharar bakery is donating 40kg of untouched surplus bread & food items to night shelter homes. Seeking 2 heroes with vehicles to transport items before 9 PM.',
    category: 'Community Welfare 🤝',
    cityId: 'city_kharar',
    cityName: 'Kharar',
    localityId: 'loc_kh_landran',
    localityName: 'Landran Road',
    approxAddress: 'Landran Road Bakery Hub',
    latitude: 30.7340,
    longitude: 76.6690,
    budget: 0,
    creditReward: 300,
    urgency: 'TODAY',
    estimatedDuration: '~1 hour',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    distanceKm: 1.5,
    isCommunityEvent: true,
    eventDate: 'TODAY • 8:30 PM',
    requiredVolunteers: 3,
    joinedVolunteersCount: 2
  },

  // --- MOHALI (Civic Drives & Environmental Projects) ---
  {
    id: 'gig_mo_1',
    posterId: 'user_shalok',
    posterName: 'Shalok Dadhwal',
    posterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.9,
    posterGigCount: 18,
    title: 'Phase 3B2 Neighborhood Park Tree Plantation Drive',
    description: 'Join our Green Mohali Drive! Planting 50 native Neem, Amaltas & Jamun tree saplings around Phase 3B2 public park. Saplings, soil & tools provided. Bring your friends!',
    category: 'Environmental 🌿',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p3b2',
    localityName: 'Phase 3B2',
    approxAddress: 'Phase 3B2 Main Community Park',
    latitude: 30.7105,
    longitude: 76.7170,
    budget: 0,
    creditReward: 350,
    urgency: 'SOON',
    estimatedDuration: '~2 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
    distanceKm: 2.2,
    isCommunityEvent: true,
    eventDate: 'SUNDAY • 7:30 AM',
    requiredVolunteers: 15,
    joinedVolunteersCount: 9
  },
  {
    id: 'gig_mo_2',
    posterId: 'user_simran',
    posterName: 'Simran Kaur',
    posterAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    posterRating: 5.0,
    posterGigCount: 32,
    title: 'N-Choe Seasonal Stream Plastic Waste Clearance',
    description: 'Polythene bags & plastic bottles clogged the N-Choe stream bed near Sector 70. Assembling a group of 10 heroes with boots & grabbers to clear a 100m stream stretch.',
    category: 'Civic Clean Drive 🧹',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_sec70',
    localityName: 'Sector 70',
    approxAddress: 'N-Choe Bridge, Sector 70, Mohali',
    latitude: 30.7020,
    longitude: 76.7010,
    budget: 0,
    creditReward: 400,
    urgency: 'SOON',
    estimatedDuration: '~2.5 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    distanceKm: 3.1,
    isCommunityEvent: true,
    eventDate: 'SATURDAY • 8:00 AM',
    requiredVolunteers: 10,
    joinedVolunteersCount: 6
  },
  {
    id: 'gig_mo_3',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Free Digital Literacy & Cyber Safety for Elders',
    description: 'Conducting a friendly 1-hour workshop at Phase 7 Senior Citizen Club to teach elders how to detect spam scams, use UPI securely, and consult doctors online.',
    category: 'Community Welfare 🤝',
    cityId: 'city_mohali',
    cityName: 'Mohali',
    localityId: 'loc_mo_p7',
    localityName: 'Phase 7',
    approxAddress: 'Phase 7 Senior Citizen Club, Mohali',
    latitude: 30.7040,
    longitude: 76.7120,
    budget: 0,
    creditReward: 250,
    urgency: 'FLEXIBLE',
    estimatedDuration: '~1.5 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 240 * 60000).toISOString(),
    distanceKm: 2.8
  },

  // --- CHANDIGARH (Environmental & Public Safety) ---
  {
    id: 'gig_ch_1',
    posterId: 'user_arjun',
    posterName: 'Arjun Mehta',
    posterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    posterRating: 4.8,
    posterGigCount: 45,
    title: 'Sukhna Lake Bird Sanctuary Plastic Awareness Drive',
    description: 'Distributing 500 recycled cloth bags to evening visitors at Sukhna Lake to prevent single-use plastic dumping in bird sanctuary zones. 8 volunteers needed!',
    category: 'Environmental 🌿',
    cityId: 'city_chandigarh',
    cityName: 'Chandigarh',
    localityId: 'loc_ch_sec17',
    localityName: 'Sector 17 (City Center)',
    approxAddress: 'Sukhna Lake Promenade, Chandigarh',
    latitude: 30.7410,
    longitude: 76.7850,
    budget: 0,
    creditReward: 350,
    urgency: 'SOON',
    estimatedDuration: '~2 hours',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 150 * 60000).toISOString(),
    distanceKm: 5.2,
    isCommunityEvent: true,
    eventDate: 'SUNDAY • 4:00 PM',
    requiredVolunteers: 8,
    joinedVolunteersCount: 5
  }
];

export const INITIAL_REWARDS_SEED: RewardItem[] = [
  {
    id: 'reward_cafe_100',
    name: '₹100 Local Café Voucher',
    description: 'Redeemable for artisanal coffee, cold brew, or shakes at partner cafés across Kharar, Mohali & Chandigarh.',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=80',
    creditCost: 500,
    stock: 45,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Brew & Bean Co.',
    redemptionInstructions: 'Show the generated 8-digit voucher code to the cashier before placing your order.',
    isActive: true
  },
  {
    id: 'reward_hero_stickers',
    name: 'Neighborhood Hero Sticker Pack',
    description: 'High-quality waterproof vinyl stickers featuring original Neighborhood Hero emblems for laptops & helmets.',
    imageUrl: 'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=400&q=80',
    creditCost: 1000,
    stock: 20,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Collect from your nearest community hub or provide postal address upon redemption.',
    isActive: true
  },
  {
    id: 'reward_hero_tshirt',
    name: 'Branded Hero Tech T-Shirt',
    description: 'Breathable dry-fit black graphic t-shirt with electric cyan Hero insignia on chest.',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    creditCost: 1500,
    stock: 12,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Select your size (S, M, L, XL) and pick up at the weekly Tricity Hero meetup.',
    isActive: true
  },
  {
    id: 'reward_dining_500',
    name: '₹500 Tricity Restaurant Pass',
    description: 'Enjoy ₹500 discount on your bill at select top-rated dining spots in Sector 35 Chandigarh & Phase 3B2 Mohali.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    creditCost: 2000,
    stock: 8,
    cityIds: ['city_mohali', 'city_chandigarh'],
    partnerName: 'Tricity Gourmet Club',
    redemptionInstructions: 'Present digital coupon at billing. Valid on minimum bill of ₹800.',
    isActive: true
  },
  {
    id: 'reward_hero_jacket',
    name: 'Premium Hero Windbreaker Jacket',
    description: 'Exclusive waterproof urban reflector jacket awarded to high-tier community champions.',
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=400&q=80',
    creditCost: 5000,
    stock: 3,
    cityIds: ['city_kharar', 'city_mohali', 'city_chandigarh', 'city_panchkula'],
    partnerName: 'Neighborhood Hero Store',
    redemptionInstructions: 'Admin team will contact you directly for custom sizing and doorstep delivery.',
    isActive: true
  }
];

export const INITIAL_TRANSACTIONS_SEED: CreditTransaction[] = [
  {
    id: 'tx_init_1',
    userId: 'user_shalok',
    amount: 500,
    type: 'EARN',
    reason: 'Completed 15 neighborhood missions',
    createdAt: '2026-08-01T12:00:00Z'
  },
  {
    id: 'tx_init_2',
    userId: 'user_shalok',
    amount: 100,
    type: 'BONUS',
    reason: 'First Mission & 5-Star Streak Bonuses',
    createdAt: '2026-08-10T14:30:00Z'
  },
  {
    id: 'tx_init_3',
    userId: 'user_shalok',
    amount: 120,
    type: 'EARN',
    reason: 'Completed Python Tutoring & Grocery Tasks',
    createdAt: '2026-08-18T09:15:00Z'
  }
];
